import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "@/components/server/Nav/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="pt-10">
        <Nav />
        {children}
      </body>
    </html>
  );
}
